### ISSUE TITLE
Bugs: [Papers] The display of citations does not follow the change of source

### ISSUE THREAD

**Issue by bepolymathe** [SeptemberHX/joplin-plugin-bundle#24]
Hi @SeptemberHX 

When I have several references in the same document, I can only display annotations from the first...

[Capture vidéo du 28-10-2022 10:43:31.webm](https://user-images.githubusercontent.com/29939805/198545036-c31a2503-69c9-4f9e-ad4c-4e4c753e1247.webm)

**Comment by SeptemberHX** [comment]
It should be fixed now. There should be a small delay (~5s, depends on your network)for the notes updating because it needs to send request to zotero servers for note data.

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/10253504/com.septemberhx.pluginBundle.jpl.zip)
